// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOleHf5P5g1_NrgbCU4wJB46_d5l0IfY',
    appId: '1:527878866066:web:194ca47103c89413b5d24b',
    messagingSenderId: '527878866066',
    projectId: 'authentications-6b509',
    authDomain: 'authentications-6b509.firebaseapp.com',
    storageBucket: 'authentications-6b509.appspot.com',
    measurementId: 'G-LVCLJJFYPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDlhP5IHisFKzZNelMirEvanwlM-NMTho',
    appId: '1:527878866066:android:ab9d7513c1b236d3b5d24b',
    messagingSenderId: '527878866066',
    projectId: 'authentications-6b509',
    storageBucket: 'authentications-6b509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASS4HWdh_m_phOUkrLBjn4mx_qnXGhzy8',
    appId: '1:527878866066:ios:927a825013bcfa27b5d24b',
    messagingSenderId: '527878866066',
    projectId: 'authentications-6b509',
    storageBucket: 'authentications-6b509.appspot.com',
    androidClientId: '527878866066-lg5mad837p8urpn0122fml8m99f9gqdq.apps.googleusercontent.com',
    iosClientId: '527878866066-aq02ea8ccqe66mpik6v8782lrsmc7q9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividad1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASS4HWdh_m_phOUkrLBjn4mx_qnXGhzy8',
    appId: '1:527878866066:ios:927a825013bcfa27b5d24b',
    messagingSenderId: '527878866066',
    projectId: 'authentications-6b509',
    storageBucket: 'authentications-6b509.appspot.com',
    androidClientId: '527878866066-lg5mad837p8urpn0122fml8m99f9gqdq.apps.googleusercontent.com',
    iosClientId: '527878866066-aq02ea8ccqe66mpik6v8782lrsmc7q9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividad1',
  );
}
